site_name: OR Editions
site_description: PDF originaux libres de droits
site_author: Olivier Rey
copyright: Copyright Olivier Rey 2007-2019 - Site sous licence GNU FDL V3
google_analytics: ['UA-110156293-1', 'orey.github.io']
theme: readthedocs
site_dir: site
nav:
- 'Home': 'index.md'
- 'Publications':
    - 'Anatole Swadock, Trucs de bouse': 'pages/OR01.md'
    - 'Anatole Swadock, Petits poèmes géologiques': 'pages/OR02.md'
    - 'Emile Lyre, Le voyage philosophique': 'pages/OR03.md'
    - 'Al Zeituni, Quatrains': 'pages/OR05.md'
    - 'Emile Lyre, Journal de miniatures': 'pages/OR07.md'
- 'Textes en français':
    - 'Plaine': 'textes/plaine.md'
- 'English Texts':
    - 'Remembering My Friend': 'texts/20190821.md'
    - 'Empty Shelf': 'texts/20190720.md'
    - 'Coming Back From A Long Travel': 'texts/20190608.md'
    - 'Did They Forget?': 'texts/20171125.md'
    - 'How Could I?': 'texts/20170827.md'
    - 'What Remains Of Wise Men?': 'texts/20161220.md'
    - 'Teaching Equilibrium': 'texts/20161203.md'
    - 'Ode To The Whirling Player': 'texts/20161126.md'
    - 'The Imbalance Fixer': 'texts/20161116.md'
    - 'As It Is Supposed To Be': 'texts/20160810.md'
- 'A propos':
    - 'A propos': 'about/about.md'
    - 'License': 'about/LICENSE.md'
